export type ProductImage = {
  id: number;
  imageUrl: string;
  isPrimary: boolean;
};

export type Product = {
  id: number;
  sku: string;
  name: string;
  description: string;
  primaryImageUrl: string | null;
  images: ProductImage[];
  price: number;
  compareAtPrice?: number | null;
  salePrice?: number | null;
  costPrice?: number | null;
  currency: string;
  stock: number;
  infiniteStock: boolean;
  showPriceInStore: boolean;
  barcode?: string | null;
  weightKg?: number | null;
  lengthCm?: number | null;
  widthCm?: number | null;
  heightCm?: number | null;
  freeShipping: boolean;
  featuredProduct: boolean;
  tags?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  relatedProductIds?: number[];
  complementaryProductIds?: number[];
  categoryId?: number | null;
  categoryName?: string | null;
  brandId?: number | null;
  brandName?: string | null;
  color?: string | null;
  sizeOptions?: string | null;
  material?: string | null;
  gender?: string | null;
  promoText?: string | null;
  socialProof?: string | null;
  videoUrl?: string | null;
  productType?: 'PHYSICAL' | 'DIGITAL';
  isNew: boolean;
  active: boolean;
};

export type CreateProductRequest = {
  sku?: string | null;
  name: string;
  description?: string;
  price: number;
  compareAtPrice?: number | null;
  salePrice?: number | null;
  showPriceInStore?: boolean;
  costPrice?: number | null;
  currency: string;
  stock: number;
  infiniteStock: boolean;
  barcode?: string;
  weightKg?: number;
  lengthCm?: number;
  widthCm?: number;
  heightCm?: number;
  freeShipping?: boolean;
  featuredProduct?: boolean;
  tags?: string;
  seoTitle?: string;
  seoDescription?: string;
  relatedProductIds?: number[];
  complementaryProductIds?: number[];
  categoryId?: number | null;
  brandId?: number | null;
  color?: string;
  sizeOptions?: string;
  material?: string;
  gender?: string;
  promoText?: string;
  socialProof?: string;
  productType?: 'PHYSICAL' | 'DIGITAL';
  videoUrl?: string;
  isNew?: boolean;
  initialVariants?: Array<Record<string, unknown>>;
};

export type ProductListFilters = {
  search?: string;
  categoryId?: number;
  brandId?: number;
  stockStatus?: 'IN_STOCK' | 'OUT_OF_STOCK' | 'BY_QUANTITY';
  priceType?: 'PROMOTIONAL' | 'NON_PROMOTIONAL';
  visibility?: 'VISIBLE' | 'HIDDEN';
  shippingPromotion?: 'FREE_SHIPPING' | 'NO_FREE_SHIPPING';
  weightDimensions?: 'WITHOUT_DIMENSIONS' | 'WITHOUT_WEIGHT' | 'WITHOUT_WEIGHT_AND_DIMENSIONS';
};
